name: Scheduled check
permissions:
  packages: write
  contents: read

on:
  schedule:
    - cron:  '30 2 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: ./build.sh
        shell: bash
        env: 
          SCR_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}